image: node:8-alpine
services:
  - mongo:3.6-jessie

stages:
  - build
  - deploy

before_script:
  - npm install -g bread

build:
  script:
    - bread
  stage: build
  only:
    - feature/gitlab-ci
  tags:
    - docker
    - node
    - mongo

deploy:
  script:
    - echo 'empy job'
  stage: build
  only:
    - feature/gitlab-ci
  tags:
    - docker
