image: maven:3.6-jdk-8

before_script:
  - "apt-get update"
  - "apt-get -qq -y install pandoc rsync"
  - "eval $(ssh-agent -s)"
  - "echo \"$SSH_PRIVATE_KEY\" | ssh-add - > /dev/null"
  - "mkdir -p ~/.ssh"
  - "[[ -f /.dockerenv ]] && echo \"$SSH_SERVER_HOSTKEYS\" > ~/.ssh/known_hosts"

deploy:
  script:
    - "mvn -B package | grep --color=never sokrates"
    - "rsync -avr --delete-after --chmod 777 target/sokrates/ pvo@vorba.ch:/var/www/vorba.ch/"
  only:
    - master
  tags:
    - docker
