image: "alpine:latest"

before_script:
  - "apk update"
  - "apk add openssh rsync"

deploy:
  script:
    - "rsync -r --chown www-data:www-data --chmod 755 public/ pvo@vorba.ch:~/vorba.ch/"
  only:
    - "feature/gitlab-ci"
  tags:
    - docker
