logging.level:
  root: WARN
  de.vorb.sokrates: INFO
  org.jooq.Constants: INFO

spring.datasource:
  url: jdbc:h2:./sokrates
  driver-class-name: org.h2.Driver
  username: sa
  password:

sokrates:
  site:
    title: vorba.ch
    default-locale: en-US
    translations: src/site/resources/translations
    properties:
      hostname: vorba.ch
  directory:
    templates: src/site/templates/
  generator:
    pandoc-executable: /usr/bin/pandoc
    extension-mapping:
      md: html
    generate-rules:
      - pattern: src/site/posts/{year:(2012|2013)}/*.md
        base-directory: src/site/posts
        format: markdown
    copy-rules:
      - pattern: src/site/posts/**/*
        base-directory: src/site/posts
    tag-rule:
      source-file-pattern: "src/site/tags/%s.md"
      output-file-pattern: "tag/%s.html"
      format: markdown
      template: tag.ftl
      index-output-file: tags/index.html
      index-template: tag-index.ftl
  indexes:
    - name: Blog index
      title: Blog index
      template: index.ftl
      output-file: index.html
      order-by:
        - created_at DESC
      grouping: BY_YEAR_CREATED
    - name: Feed
      title: Atom Feed
      template: feed.ftl
      output-file: feed.xml
      order-by:
        - created_at DESC
      limit: 10
